# Generated by Django 3.2 on 2022-01-23 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otp_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='receiver',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
