# Generated by Django 3.2 on 2022-01-23 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(upload_to='Category_Icon')),
                ('wallpaper', models.ImageField(default=' ', upload_to='Category_Wallpaper')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Professionals_photo')),
                ('service_charge', models.CharField(blank=True, max_length=10, null=True)),
                ('job_completed', models.IntegerField(default=0)),
                ('contact_number1', models.CharField(max_length=13)),
                ('contact_number2', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.TextField(blank=True, default=' ', null=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=2000)),
                ('select_type', models.CharField(choices=[('single', 'Single Correct'), ('multi', 'Multi Correct'), ('form', 'Form')], max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('parent_question', models.IntegerField(blank=True, null=True)),
                ('parent_option', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='ValueOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=500)),
                ('factor', models.FloatField(default=1.0)),
                ('price', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.TextField(blank=True, default=' ', null=True)),
                ('street', models.TextField(default=' ')),
                ('city', models.TextField(default=' ')),
                ('postal_code', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('state', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='Subcategory_Icons')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'unique_together': {('category', 'subcategory')},
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('service_time', models.CharField(blank=True, max_length=50, null=True)),
                ('service_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Declined', 'Declined'), ('Completed', 'Completed')], max_length=100, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('professional_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.professionals')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='professionals',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='main.SubCategory'),
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_question', models.IntegerField(blank=True, default=0, null=True)),
                ('choice', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
            ],
        ),
    ]
