# Generated by Django 3.2.2 on 2022-02-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otps',
            name='receiver',
        ),
    ]
