# Generated by Django 3.2 on 2022-01-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
        ('main', '0003_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='b2b.company'),
            preserve_default=False,
        ),
    ]
