# Generated by Django 3.2 on 2022-01-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
        ('main', '0004_companydetails_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.BooleanField(default=False)),
                ('offline_payment', models.BooleanField(default=False)),
                ('paytm', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_operation', to='b2b.company')),
            ],
        ),
        migrations.CreateModel(
            name='FoundingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('images', models.ImageField(upload_to='Subcategory_Icons')),
                ('about', models.TextField(blank=True, default=' ', null=True)),
                ('title', models.CharField(max_length=40)),
                ('linkedin', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=60)),
                ('twitter', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='companydetails',
            old_name='name',
            new_name='tittle',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='sent_on',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='about',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='address',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='favicon',
            field=models.ImageField(default='', upload_to='favicon'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(default='', upload_to='logo'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='mobile_number1',
            field=models.CharField(default='', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='mobile_number2',
            field=models.CharField(default='', max_length=13, unique=True),
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='b2b.company')),
            ],
        ),
        migrations.CreateModel(
            name='razorpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('company_operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_operations_razorpay', to='main.companyoperation')),
            ],
        ),
        migrations.CreateModel(
            name='Paytm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('merchant_key', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('merchant_web', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('industry_type_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('company_operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_operations_paytm', to='main.companyoperation')),
            ],
        ),
    ]
